# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d094cf5bb09ad03780d8bfe7ce94e0ce3a92f54c7926ebeb9e1ffc6dedb539e5ef7fd38ef470529d23dc3cdc8193505474b48d02630637cc155eb5c09acbaf4

test:
  secret_key_base: 6da7631dcbf5f8b3c872fbb6fbee97b6690b4915eeac22f9e0c6bf2c1a16c733251d6ed15b72cdadd67c6e9b74a5ff233eec64bee17d8079aafdddeb3d820f90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
